CREATE DATABASE Project_2;

USE Project_2;

SELECT * FROM ShopKart_Orders;

--Phase 1 — Import & Understand Data .....................................

--1.Total number of records
SELECT COUNT(OrderID) 
FROM ShopKart_Orders;

--2.Column names
sp_help ShopKart_Orders;

--3.Data types
sp_help ShopKart_Orders;

--4.Minimum and maximum OrderDate
SELECT MAX(OrderDate) AS MAX_Date,
		MIN(OrderDate) AS MIN_Date
FROM ShopKart_Orders;

--5.Number of unique customers
SELECT COUNT(DISTINCT CustomerID) AS Unique_Customer
FROM ShopKart_Orders;

--6.Number of unique products
SELECT COUNT(DISTINCT ProductName) AS Unique_Products
FROM ShopKart_Orders;

--7.Number of cities
SELECT COUNT(DISTINCT City) AS Cities
FROM ShopKart_Orders;

--8.Number of cancelled orders
SELECT COUNT(*) AS Cancelled_Orders
FROM ShopKart_Orders
WHERE OrderStatus = 'Cancelled';

--9.Number of returned orders
SELECT COUNT(*) AS Returned_Orders
FROM ShopKart_Orders
WHERE OrderStatus = 'Returned'

--10.Check whether any important columns contain NULL
SELECT *
FROM ShopKart_Orders
WHERE OrderID IS NULL
   OR OrderDate IS NULL
   OR CustomerID IS NULL
   OR ProductID IS NULL
   OR Quantity IS NULL
   OR Revenue IS NULL
   OR Profit IS NULL;

-- Question 2 — Customer Analysis ................................

--How many unique customers placed orders in each city?
SELECT City , COUNT(DISTINCT CustomerID) AS Unique_Customers
FROM ShopKart_Orders
GROUP BY City;

--Question 3 — City with the highest customers ..............................

--"Which city has the highest number of unique customers?"
SELECT TOP 1 
       City,
       COUNT(DISTINCT CustomerID) AS Unique_Customers
FROM ShopKart_Orders
GROUP BY City
ORDER BY Unique_Customers DESC;

--Question 4 — Revenue Analysis

--What is the total Revenue generated by each city?
SELECT City,SUM(Revenue) AS TotalRevenue
FROM ShopKart_Orders
GROUP BY City;

--Question 5 — Highest Revenue City

--"Which city generated the highest total revenue?"
SELECT TOP 1 City,SUM(Revenue) AS Total_Revenue
FROM ShopKart_Orders
GROUP BY City
ORDER BY Total_Revenue DESC;

--Question 6 — Product Performance

--Which product generated the highest total revenue?
SELECT TOP 1 ProductName,SUM(Revenue) AS Total_Revenue
FROM ShopKart_Orders
GROUP BY ProductName
ORDER BY Total_Revenue DESC;

--Question 7 — Profit Analysis

--"Which product generated the highest total profit?"
SELECT TOP 1 ProductName,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY ProductName
ORDER BY Total_Profit DESC;

--Question 8 — Category Analysis

--Show total Revenue and total Profit for each Product Category.
SELECT Category,
    SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY Category;

--Question 9 — Best Category by Profit

--Which product category generated the highest total profit?
SELECT TOP 1 
    Category,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY Category
ORDER BY Total_Profit DESC;

--Question 10 — Quantity Analysis

--Which product has sold the highest total quantity?
SELECT TOP 1 
    ProductName,
    SUM(Quantity) AS Total_Quantity
FROM ShopKart_Orders
GROUP BY ProductName
ORDER BY Total_Quantity DESC;

--Question 11 — Monthly Sales Analysis

--How much total revenue did ShopKart generate in each month?
SELECT MONTH(OrderDate) AS Month,
    YEAR(OrderDate) AS Year,
    SUM(Revenue) AS Total_Revenue
FROM ShopKart_Orders
GROUP BY MONTH(OrderDate),YEAR(OrderDate)
ORDER BY Year,Month

--Question 12 — Highest Revenue Month

--Which month and year generated the highest total revenue?
USE Project_2;

SELECT TOP 1 
    MONTH(OrderDate) AS Month,
    YEAR(OrderDate) AS Year,
    SUM(Revenue) AS Total_Revenue
FROM ShopKart_Orders
GROUP BY MONTH(OrderDate),YEAR(OrderDate)
ORDER BY Total_Revenue DESC;

--Question 13 — Year-over-Year Analysis

--What was the total revenue generated in each year?
SELECT YEAR(OrderDate) AS Year,
    SUM(Revenue) AS Total_Revenue
FROM ShopKart_Orders
GROUP BY YEAR(OrderDate);

--Question 14 — Year with Highest Profit

--Which year generated the highest total profit?
SELECT TOP 1
    YEAR(OrderDate) AS Year,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY YEAR(OrderDate)
ORDER BY Total_Profit DESC;

--Question 15 — Average Order Value

--What is the average Revenue per order?
SELECT AVG(Revenue) AS Average_Revenue
FROM ShopKart_Orders;

--Question 16 — Average Order Value by City

--What is the average Revenue per order for each city?
SELECT City,
    AVG(Revenue) AS Average_Revenue
FROM ShopKart_Orders
GROUP BY City;

--Question 17 — Most Valuable Customer

--Which customer generated the highest total revenue?
    SELECT TOP 1
        CustomerID,
        SUM(Revenue) AS Total_Revenue
    FROM ShopKart_Orders
    GROUP BY CustomerID
    ORDER BY Total_Revenue DESC;

--Question 18 — Top 5 Customers

--Show me the top 5 customers by total revenue.
    SELECT TOP 5
        CustomerID,
        SUM(Revenue) AS Total_Revenue
    FROM ShopKart_Orders
    GROUP BY CustomerID
    ORDER BY Total_Revenue DESC;

--Question 19 — Customer Orders

--Which customer placed the highest number of orders?
SELECT TOP 1
    CustomerID,
    COUNT(CustomerID) AS Total_Orders
FROM ShopKart_Orders
GROUP BY CustomerID
ORDER BY Total_Orders DESC;

--Question 20 — Top 5 Customers by Number of Orders

--Show the top 5 customers who placed the highest number of orders.
SELECT TOP 5
    CustomerID,
    COUNT(CustomerID) AS Total_Orders
FROM ShopKart_Orders
GROUP BY CustomerID
ORDER BY Total_Orders DESC;

--Question 21 — Customer Profitability

--Which customer generated the highest total profit?
SELECT TOP 1
    CustomerID,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY CustomerID
ORDER BY Total_Profit DESC;

--Question 22 — Repeat Customers

--How many customers placed more than 10 orders?"
SELECT COUNT(*) AS Customers_More_Than_10_Orders
FROM 
(
    SELECT CustomerID
    FROM ShopKart_Orders
    GROUP BY CustomerID
    HAVING COUNT(OrderID) > 10
) AS CustomersOrders;

--Question 23 — High-Value Customers

--Find all customers whose total revenue is greater than ₹1,00,000.
SELECT CustomerID,
    SUM(Revenue) AS Total_Revenue
FROM ShopKart_Orders
GROUP BY CustomerID
HAVING SUM(Revenue) > 100000;

--Question 24 — Category Profit Margin

--Calculate the profit margin percentage for each product category.
USE Project_2;

SELECT Category,
    SUM(Profit) AS Total_Profit,
    SUM(Revenue) AS Total_Revenue,
    CAST(SUM(Profit)/SUM(Revenue)*100.0 AS DECIMAL(10,2)) AS Profit_Margin
FROM ShopKart_Orders
GROUP BY Category;

--Question 25 — Best Profit Margin Category

--Which product category has the highest profit margin percentage?
SELECT TOP 1
    Category,
    SUM(Profit) AS Total_Profit,
    SUM(Revenue) AS Total_Revenue,
    CAST(SUM(Profit)/SUM(Revenue)*100.0 AS DECIMAL(10,2)) AS Profit_Margin
FROM ShopKart_Orders
GROUP BY Category 
ORDER BY Profit_Margin DESC;

--Question 26 — Revenue by Payment Method

--How much total revenue was generated through each payment method?
SELECT PaymentMethod,
    SUM(Revenue) AS Total_Revenue
FROM ShopKart_Orders
GROUP BY PaymentMethod;

--Question 27 — Most Used Payment Method

--Which payment method was used for the highest number of orders?
SELECT TOP 1
    PaymentMethod,
    COUNT(OrderID) AS Total_Orders
FROM ShopKart_Orders
GROUP BY PaymentMethod
ORDER BY Total_Orders DESC;

--Question 28 — Order Status Analysis

--Show the number of orders for each OrderStatus.
SELECT OrderStatus,
    COUNT(OrderID) AS Total_OrderID
FROM ShopKart_Orders
GROUP BY OrderStatus;

--Question 29 — Cancellation Rate

--What percentage of all orders were cancelled?
USE Project_2;

SELECT 
    SUM(CASE 
            WHEN OrderStatus = 'Cancelled' THEN 1 
            ELSE 0 
        END) * 100.0 / COUNT(OrderID) AS Cancellation_Rate
FROM ShopKart_Orders;

--Question 30 — Return Rate

--What percentage of all orders were returned?
SELECT 
    SUM(CASE
            WHEN OrderStatus = 'Returned' THEN 1
            ELSE 0
        END) * 100.0 / COUNT(OrderID) AS Returned_Rate
FROM ShopKart_Orders;

--Question 31 — Cancellation vs Return Rate

--Show the Cancellation Rate and Return Rate in a single result.
SELECT 
    SUM(CASE
            WHEN OrderStatus = 'Cancelled' THEN 1 
            ELSE 0
        END) * 100.0 / COUNT(OrderID) AS Cancellation_Rate,

    SUM(CASE
            WHEN OrderStatus ='Returned' THEN 1
            ELSE 0
        END) * 100.0 / COUNT(OrderID) AS Returned_Rate

FROM ShopKart_Orders;
    
--Question 32 — Cancellation Rate by City

--What is the cancellation rate for each city?
SELECT City,
    SUM(CASE
            WHEN OrderStatus = 'Cancelled' THEN 1
            ELSE 0
        END) * 100.0 / COUNT(OrderID) AS Cencellation_Rate
FROM ShopKart_Orders
GROUP BY City;

--Question 33 — Highest Cancellation Rate City

--Which city has the highest cancellation rate?
SELECT TOP 1
    City,
    SUM(CASE
            WHEN OrderStatus = 'Cancelled' THEN 1
            ELSE 0
        END) * 100.0 / COUNT(OrderID) AS Cancellation_Rate
FROM ShopKart_Orders
GROUP BY City
ORDER BY Cancellation_Rate DESC;

--Question 34 — Revenue by Order Status

--How much total revenue comes from each order status?
SELECT OrderStatus,
    SUM(Revenue) AS Total_Revenue
FROM ShopKart_Orders
GROUP BY OrderStatus;

--Question 35 — Revenue from Delivered Orders

--What is the total revenue generated from only Delivered orders?
SELECT OrderStatus,
    SUM(Revenue) AS Total_Revenue
FROM ShopKart_Orders
GROUP BY OrderStatus
HAVING OrderStatus = 'Delivered'

--Question 36 — Average Revenue by Order Status

--What is the average revenue per order for each OrderStatus?
SELECT OrderStatus,
    AVG(Revenue) AS Average_Revenue
FROM ShopKart_Orders
GROUP BY OrderStatus;

--Question 37 — Profit by Order Status

--What is the total profit generated by each OrderStatus?
SELECT 
    OrderStatus,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY OrderStatus;

--Question 38 — Most Profitable Order Status

--Which OrderStatus generated the highest total profit?
SELECT TOP 1
    OrderStatus,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY OrderStatus
ORDER BY Total_Profit DESC;

--Question 39 — Monthly Profit Analysis

--What is the total profit generated in each month and year?
SELECT 
    MONTH(OrderDate) AS Month,
    YEAR(OrderDate) AS Year,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY MONTH(OrderDate),YEAR(OrderDate)
ORDER BY Year,Month;

--Question 40 — Highest Profit Month

--Which month and year generated the highest total profit?
SELECT TOP 1
    MONTH(OrderDate) AS Month,
    YEAR(OrderDate) AS Year,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY MONTH(OrderDate),YEAR(OrderDate)
ORDER BY Total_Profit DESC;

--Question 41 — Average Profit per Order

--What is the average profit generated per order?
USE Project_2;

SELECT AVG(Profit) AS Average_Profit
FROM ShopKart_Orders;

--Question 42 — Average Profit by Category

--"What is the average profit per order for each product category?"
SELECT 
    Category,
    AVG(Profit) AS Average_Profit
FROM ShopKart_Orders
GROUP BY Category;

--Question 43 — Highest Average Profit Category

--Which product category has the highest average profit per order?
SELECT TOP 1
    Category,
    AVG(Profit) AS Average_Profit
FROM ShopKart_Orders
GROUP BY Category
ORDER BY Average_Profit DESC;

--Question 44 — Customer Average Order Value

--What is the average revenue per order for each customer?
SELECT 
    CustomerID,
    AVG(Revenue) AS Average_Revenue
FROM ShopKart_Orders
GROUP BY CustomerID;

--Question 45 — Highest Average Order Value Customer

--Which customer has the highest average revenue per order?
SELECT TOP 1
    CustomerID,
    AVG(Revenue) AS Average_Revenue
FROM ShopKart_Orders
GROUP BY CustomerID
ORDER BY Average_Revenue DESC;

--Question 46 — Customer with Highest Total Quantity

--Which customer purchased the highest total quantity of products?
SELECT TOP 1
    CustomerID,
    SUM(Quantity) AS Total_Quantity
FROM ShopKart_Orders
GROUP BY CustomerID
ORDER BY Total_Quantity DESC;

--Question 47 — Top 5 Customers by Total Quantity

--Show the top 5 customers by total quantity purchased.
SELECT TOP 5
    CustomerID,
    SUM(Quantity) AS Total_Quantity
FROM ShopKart_Orders
GROUP BY CustomerID
ORDER BY Total_Quantity DESC;

--Question 48 — Product Sales by Quantity

--Show the total quantity sold for each product, along with its total revenue and total profit.
SELECT 
    ProductName,
    SUM(Quantity) AS Total_Quantity,
    SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY ProductName;

--Question 49 — Best-Selling Product by Quantity

--Which product sold the highest number of units?
SELECT TOP 1
    ProductName,
    SUM(Quantity) AS Total_Units
FROM ShopKart_Orders
GROUP BY ProductName
ORDER BY Total_Units DESC;

--Question 50 — Product with Highest Revenue per Unit

--Which product generated the highest average revenue per unit sold?
SELECT TOP 1
    ProductName,
    SUM(Revenue) * 1.0 / SUM(Quantity) Revenue_Per_Unit
FROM ShopKart_Orders
GROUP BY ProductName
ORDER BY Revenue_Per_Unit DESC;

--Question 51 — Product with Highest Profit per Unit

--Which product generated the highest profit per unit sold?
USE Project_2;

SELECT TOP 1
    ProductName,
    SUM(Profit) * 1.0 / SUM(Quantity) AS Profit_Per_Unit
FROM ShopKart_Orders
GROUP BY ProductName
ORDER BY Profit_Per_Unit DESC;

--Question 52 — Customer Profitability

--Show the top 5 customers by total profit, along with their total revenue.
SELECT TOP 5
    CustomerID,
    SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit
FROM ShopKart_Orders
GROUP BY CustomerID
ORDER BY Total_Profit DESC;

--Question 53 — Customer Profit Margin

--Calculate the profit margin percentage for each customer.
SELECT CustomerID,
    SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    CAST(SUM(Profit)*100.0 / SUM(Revenue) AS DECIMAL(10,2) )AS Profit_Margin
FROM ShopKart_Orders
GROUP BY CustomerID;

 --Question 54 — Most Profitable Customer by Margin

 --Which customer has the highest profit margin percentage?
SELECT TOP 1
    CustomerID,
    SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    CAST(SUM(Profit)*100.0 / SUM(Revenue) AS DECIMAL(10,2) )AS Profit_Margin
FROM ShopKart_Orders
GROUP BY CustomerID
ORDER BY Profit_Margin DESC;

--Question 55 — Top 5 Products by Profit Margin

--Show the top 5 products with the highest profit margin percentage.
SELECT TOP 5
    ProductName,
    SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    CAST(SUM(Profit)*100.0 / SUM(Revenue) AS DECIMAL(10,2) )AS Profit_Margin
FROM ShopKart_Orders
GROUP BY ProductName
ORDER BY Profit_Margin DESC;

--Question 56 — Low-Margin Products

--Find all products whose profit margin is less than 10%.
SELECT
    ProductName,
    SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    CAST(SUM(Profit)*100.0 / SUM(Revenue) AS DECIMAL(10,2) )AS Profit_Margin
FROM ShopKart_Orders
GROUP BY ProductName
HAVING SUM(Profit)*100.0 / SUM(Revenue) < 10;

--Question 57 — High-Revenue but Low-Profit Products

--Find products that generated more than ₹1,00,000 in total revenue but have a profit margin below 10%."
SELECT
    ProductName,
    SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    CAST(SUM(Profit)*100.0 / SUM(Revenue) AS DECIMAL(10,2) )AS Profit_Margin
FROM ShopKart_Orders
GROUP BY ProductName
HAVING SUM(Revenue) > 100000 AND SUM(Profit)*100.0 / SUM(Revenue) < 10;

--Question 58 — High-Revenue Customers With Low Profit Margin

--Find customers who generated more than ₹2,00,000 in total revenue but have a profit margin below 15%.
SELECT
    CustomerID,
    SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    CAST(SUM(Profit)*100.0 / SUM(Revenue) AS DECIMAL(10,2) )AS Profit_Margin
FROM ShopKart_Orders
GROUP BY CustomerID
HAVING SUM(Revenue) > 200000 AND SUM(Profit)*100.0 / SUM(Revenue) < 15;

--Question 59 — Customer Purchase Frequency

--Find the top 5 customers who placed the highest number of orders.
SELECT TOP 5
    CustomerID,
    COUNT(OrderID) AS Total_Orders
FROM ShopKart_Orders
GROUP BY CustomerID
ORDER BY Total_Orders DESC;

--Question 60 — Loyal Customers

--Find all customers who placed at least 20 orders.
SELECT CustomerID,
    COUNT(OrderID) AS Total_Orders
FROM ShopKart_Orders
GROUP BY CustomerID
HAVING COUNT(OrderID) >= 20;